name: CMake

on: [push]

jobs:
  build:
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        buildtype: [Debug]
        include:
          - os: windows-latest
            platform: windows
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: macos

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
